version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "9:00"
      timezone: "America/Chicago"
    groups:
      all-actions:
        patterns: [ "*" ]