# https://github.com/actions/labeler
breaking:
- head-branch: ['breaking', 'BREAKING', 'pre/v2.0']
bug:
- head-branch: ['fix', 'FIX', 'bug', 'BUG', 'pre/v2.0']
feature:
- head-branch: ['feat', 'FEAT']
documentation:
- changed-files:
  - any-glob-to-any-file:
    - docs/**
    - images/**
    - README.md
    - CHANGELOG.md
    - CONTRIBUTING.md
enhancement:
- head-branch: ['enhance', 'improve', 'IMPR', 'DJEP']
- changed-files:
  - any-glob-to-any-file:
    - '**'
    - '!docs/**'
    - '!images/**'
    - '!README.md'
    - '!CHANGELOG.md'
    - '!CONTRIBUTING.md'
