# HOST_UID=$(id -u) HOST_GID=$(id -g) docker-compose -f docker-compose-usage.yaml up
# Linux
# docker exec -it datajoint-python_app_1 sh -c "echo 'export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/dja/.local/bin' >> /home/dja/.profile"
# docker exec -it datajoint-python_app_1 ls -la /home/dja/.local/share/datajoint-python/usage
# docker exec -it datajoint-python_app1 cat /home/dja/.local/share/datajoint-python/usage/config.json
# docker exec -it datajoint-python_app_1 pip install --upgrade git+https://github.com/guzman-raphael/otumat@usage-tracking
# docker exec -it datajoint-python_app_1 python -c 'import datajoint'
# docker exec -it datajoint-python_app_1 python -c "__import__('otumat').UsageAgent(author='DataJoint', data_directory='datajoint-python', package_name='datajoint').uninstall()"
# docker exec -it datajoint-python_app_1 python -c "__import__('otumat').UsageAgent(author='DataJoint', data_directory='datajoint-python', package_name='datajoint', host='https://fakeservices.datajoint.io:2000', install_route='/user/usage-install', event_route='/api/usage-event').send()"
# docker exec -it datajoint-python_app_1 python -c "import otumat;from datetime import datetime;otumat.UsageAgent(author='DataJoint', data_directory='datajoint-python', package_name='datajoint', host='https://fakeservices.datajoint.io:2000', install_route='/user/usage-install', event_route='/api/usage-event').recurring_send(start=datetime(2021, 4, 27, 23, 47, 30), frequency='5s')"
# docker exec -it datajoint-python_app_1 python -c "print(__import__('otumat').UsageAgent(author='DataJoint', data_directory='datajoint-python', package_name='datajoint').show_logs())"
# docker run --rm -it datajoint/mysql:5.7 mysql -htutorial-db.datajoint.io -udbadmin -pdevelop-path-area-agree -e "select * from usage_data.install;"
# docker run --rm -it datajoint/mysql:5.7 mysql -htutorial-db.datajoint.io -udbadmin -pdevelop-path-area-agree -e "select * from usage_data.event;"
# Windows
# pip install --user git+https://github.com/guzman-raphael/datajoint-python@usage-tracking
# pip install --user --upgrade --force-reinstall git+https://github.com/datajoint/otumat@usage-tracking
# python -c "import datajoint"
# python -c "print(__import__('otumat').UsageAgent(author='DataJoint', data_directory='datajoint-python', package_name='datajoint', host='https://fakeservices.datajoint.io:2000', install_route='/user/usage-install', event_route='/api/usage-event').show_logs())"
# python -c "__import__('otumat').UsageAgent(author='DataJoint', data_directory='datajoint-python', package_name='datajoint', host='https://fakeservices.datajoint.io:2000', install_route='/user/usage-install', event_route='/api/usage-event').uninstall()"
# MACOS
# pip3 install git+https://github.com/guzman-raphael/datajoint-python@usage-tracking
# python3 -c "import datajoint"
# python3 -c "__import__('otumat').UsageAgent(author='DataJoint', data_directory='datajoint-python', package_name='datajoint', host='https://fakeservices.datajoint.io:2000', install_route='/user/usage-install', event_route='/api/usage-event').uninstall()"
version: '2.4'
services:
  app:
    image: datajoint/pydev:3.6-alpine3.10
    working_dir: /src
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      - .:/src
    command:
      - sh
      - -c
      - |
        pip install .
        tail -f /dev/null
# networks:
#   default:
#     external:
#       name: datajointio_main
