# https://github.com/DavidAnson/markdownlint
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
MD007: false # Unordered list indentation
MD009: false # permit trailing spaces
MD013:
    # previously we defined line_length to 88 which is better for python
    # but not for markdown
    line_length:
        - strict: false
    tables: false # disable for tables
    headings: false # disable for headings
MD029: false # Ordered list item prefix
MD030: false # Number of spaces after a list
MD032: false # Lists should be surrounded by blank lines
MD033: # HTML elements allowed
    allowed_elements:
        - "div"
        - "span"
        - "a"
        - "br"
        - "sup"
        - "figure"
MD034: false # Bare URLs OK
MD031: false # Spacing w/code blocks. Conflicts with `??? Note` and code tab styling
MD046: false # Spacing w/code blocks. Conflicts with `??? Note` and code tab styling
