name: Close inactive issues and PRs
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 500 # API rate limit
          ## issues
          # stale
          days-before-issue-stale: 45 # for initial period, suggest 15
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 45 days with no activity."
          # close
          days-before-issue-close: 365 # for initial period, suggest 30
          close-issue-message: "This issue was closed because it has been inactive for 365 days since being marked as stale, please reopen if it's still applicable."
          ## PRs
          # stale
          days-before-pr-stale: 45 # for initial period, suggest 15
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 45 days with no activity."
          # close
          days-before-pr-close: 365 # for initial period, suggest 30
          close-pr-message: "This PR was closed because it has been inactive for 365 days since being marked as stale, please reopen if it's still applicable."
